### ISSUE TITLE
Separate function/method for checking a new test case 

### ISSUE THREAD

**Issue by IanaKhitsko** [shyasqueenslay/euro-defusion#4]
https://github.com/shyasqueenslay/euro-defusion/blob/3ee4380e468bc48fec4d4117672d3f884fed45c7/index.js#L23

Consider adding a separate function for checking a new test case without tones of comments for this)

**Comment by shyasqueenslay** [comment]
I added those not cause they are needed but for u, next time I will just skip commenting part, thx for ur notice.
