### ISSUE TITLE
Day 1

### ISSUE THREAD

**Issue by IanaKhitsko** [shyasqueenslay/euro-defusion#6]
https://github.com/shyasqueenslay/euro-defusion/blob/3ee4380e468bc48fec4d4117672d3f884fed45c7/index.js#L248

Why did you start from the day = 1 (not 0) ?

**Comment by shyasqueenslay** [comment]
Cause I do completion check before incrementing day, so: 

1. calculate day changes
2. check for completion 
3. increment day
