### ISSUE TITLE
Native forEach ? 

### ISSUE THREAD

**Issue by IanaKhitsko** [shyasqueenslay/euro-defusion#7]
https://github.com/shyasqueenslay/euro-defusion/blob/3ee4380e468bc48fec4d4117672d3f884fed45c7/index.js#L203

Can we use native forEach here?

**Comment by shyasqueenslay** [comment]
No, cause we are working with object here not array:

const balance = {a: 2, b: 3, c: 4} - it's not iterable    

Object.entries(balance) converts balance to: 
// takes all the keys of object and return those as array

['a', 'b', 'c'] -- now it's iterable
